platform:
  - x86
  - x64

environment:
  # For Python versions available on Appveyor, see
  # https://www.appveyor.com/docs/windows-images-software/#python
  matrix:
    # We use mingwpy on python 3.4 to build madx, and conda to build
    # wheels for other python versions:
    - PYVER: '3.4'
      CONDAPATH: 'C:\Miniconda34'

  global:
    MADXVER: 5.04.02
    MADXDIR: C:\madx
    COVERALLS_REPO_TOKEN:
      secure: PomPESKrst4rtCnkZOCyfyBEb03xcHzg6O0bGrYw7lf3oGWcA/ufdhu+7+shaJRF

    TWINE_USERNAME: hibtc-deploy
    TWINE_PASSWORD:
      secure: y7p5ueCXptYxkKjMeEbUHPX3+UnXM2o7KV6N5d5Pc0g=

install:
  # Log environment for informational purposes:
  - set

  # Add python and installed scripts to PATH
  - if "%PLATFORM%" == "x86" set CONDA_FORCE_32BIT=1
  - if "%PLATFORM%" == "x64" set "CONDAPATH=%CONDAPATH%-x64"
  - set "PATH=%CONDAPATH%\bin;%CONDAPATH%\Scripts;%PATH%"

  # Remove git from path, since there is a `sh.exe` here that will cause CMake
  # to complain and stop:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Configure and update conda:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # build MAD-X
  - conda create -q -n madx python=3.4
  - activate madx
  - conda install -q -c conda-forge mingwpy
  - pip install patch
  - python "utils\build_madx.py" %MADXVER% C:\ "%MADXDIR%" utils\patches

  # build cpymad
  - utils\build_wheels.bat

  # install cpymad
  - conda install -q numpy
  - pip install minrpc
  - pip install --no-index -f dist cpymad

  # Install build/test deps:
  - conda install -q coverage

build: off

test_script:
  - coverage run --source=cpymad -a test/test_util.py -v
  - coverage run --source=cpymad -a test/test_madx.py -v

after_test:
 - coverage combine
 - coveralls

artifacts:
  - path: 'dist\*.whl'
    name: wheel

deploy_script:
- ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist/*.whl }

cache:
  - '%LOCALAPPDATA%\pip\Cache'
