language: python

python:
  - "2.7"
  - "3.3"

env:
  - MADX_VERSION=5.02.04
    MADX_URL=http://madx.web.cern.ch/madx/releases

before_install:
  # install gfortran
  - sudo apt-get install gfortran

  # Download and "install" binary version from official website:
  - wget $MADX_URL/$MADX_VERSION/libmadx-linux64.so
  - wget $MADX_URL/$MADX_VERSION/madx-$MADX_VERSION.tgz
  - tar -xzf madx-$MADX_VERSION.tgz
  - sudo mv libmadx-linux64.so /usr/lib/libmadx.so
  - sudo mkdir /usr/include/madX
  - sudo mv madx-$MADX_VERSION/src/*.h /usr/include/madX

# Setup (performed within virtualenv)
install:
  # We need to install cython here, since Travis uses the checkout from the
  # repository which doesn't contain ".c" source files (unlike the source
  # distribution from PyPI):
  - pip install cython

  # Check that the source distribution can be used for installation -
  # without having any dependencies installed other than Cython:
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
  # Need to remove cpymad folder otherwise it will be imported, but we want
  # to check the version installed from the source distribution:
  - rm -r cpymad

# Actual tests:
script:
  - python test/test_resource.py
  - python test/test_madx.py
  - python test/test_model.py
  - python test/test_locator.py
