language: python

python:
  - "2.7"
  - "3.3"

env:
  global:
    - PIP_FIND_LINKS=file://$HOME/.pip-cache
    - PIP_WHEEL_DIR=$HOME/.pip-cache

before_install:
  # Install MAD-X from PPA (see https://github.com/hibtc/madx-debian):
  # if this breaks, please revert 140d5ee59abd7763464019be0bdd116dc351d7fc:
  - sudo add-apt-repository ppa:coldfix/madx -y
  - sudo apt-get update -q
  - sudo apt-get install libmadx-dev

# Setup (performed within virtualenv)
install:
  # prepare dependency cache:
  - pip wheel -v cython numpy pyyaml setuptools

  # We need to install cython here, since Travis uses the checkout from the
  # repository which doesn't contain ".c" source files (unlike the source
  # distribution from PyPI):
  - pip install cython

  # Check that the source distribution can be used for installation -
  # without having *any* dependencies installed:
  - python setup.py sdist
  - pip uninstall cython -y
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
  # Need to remove cpymad folder otherwise it will be imported, but we want
  # to check the version installed from the source distribution:
  - rm -r cpymad

  - pip install nose coverage coveralls
# Actual tests:
script:
  - coverage run --source=cpymad    test/test_resource.py -v
  - coverage run --source=cpymad -a test/test_rpc.py      -v
  - coverage run --source=cpymad -a test/test_util.py     -v
  - coverage run --source=cpymad -a test/test_madx.py     -v
  - coverage run --source=cpymad -a test/test_locator.py  -v
  - coverage run --source=cpymad -a test/test_model.py    -v

after_success:
  - coveralls

cache:
  apt: true
  directories:
    - $PIP_WHEEL_DIR
