language: python

# See: https://docs.travis-ci.com/user/languages/python/
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# - "3.7"   in `jobs`, see below!

sudo: required
dist: trusty

before_install:
  - lsb_release -a
  - env | sort

  # Install MAD-X from PPA (see https://github.com/hibtc/madx-debian):
  - sudo add-apt-repository -y ppa:coldfix/madx
  - sudo apt-get -qq update
  - sudo apt-get install -y libmadx-dev

install:
  # Check that the source distribution can be used for installation:
  - pip install cython
  - python setup.py sdist
  - pip uninstall cython -y
  - X11=0 BLAS=1 LAPACK=1 pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

  # docutils is required for `setup.py check -r`:
  - pip install flake8 docutils
  - pip install coverage coveralls

script:
  - python setup.py check -rsm
  - flake8

  # Need to remove cpymad folder otherwise it will be imported, but we want
  # to check the version installed from the source distribution:
  - rm -r cpymad
  - coverage run --source=cpymad -a test/test_util.py -v
  - coverage run --source=cpymad -a test/test_madx.py -v

after_success:
  - base=`python -c 'import os,cpymad; print(os.path.dirname(cpymad.__file__))'`/..
  - mv .git .coverage $base
  - cd $base
  - coveralls

cache:
  pip: true


# Each stage is executed only if all previous stages have succeeded:
stages:
  - test        # the default (global) stage
  - deploy      # see below

jobs:
  include:
    # Ubuntu 16.04 (Xenial Xerus) required for py3.7:
    - stage: test
      python: "3.7"
      dist: xenial

    - stage: deploy
      name: GitHub Pages
      python: "3.6"
      install:
        - pip install cython sphinx sphinx_rtd_theme
        - X11=0 BLAS=1 LAPACK=1 python setup.py develop
      script:
        - cd doc
        - make html
      after_success: true   # don't "skip"! it makes travis skip "deploy:" too!
      deploy:
        provider: pages
        local-dir: doc/_build/html
        skip-cleanup: true
        github-token:
          secure: "Z5vSkkgj12/5DdsbV0C58zO9TK4zN/f2VgQMoSNnCwEoziTN7jaLStUzIE98qpREthBUU5SE/Sd9SXEW+gW4HeryqqKI9liNb3r83jprs/Z5SsEfhEqiVXDwyidbXjn7rx+yMUUfnD+feW31fj9XiHhCE2oe7A+lFnNziVdsx8o="
        on:
          branch: master
