name: Download and prepare MAD-X sources
inputs:
  madx_version:
    description: 'MAD-X version'
    required: true

runs:
  using: composite
  steps:
    - run: git clone https://github.com/MethodicalAcceleratorDesign/MAD-X
        ../MAD-X -b "${{ inputs.madx_version }}" --depth 1
      shell: bash
    - run: patch -d ../MAD-X -p1 < .github/patch/fix-cmake-Fortran_FLAGS.patch
      shell: bash
    - name: 'Fix runtime error on macos: "Symbol not found: _mad_argc"'
      run: patch -d ../MAD-X -p1 < .github/patch/fix-macos-symbol-not-found-mad_argc.patch
      shell: bash
